package net.nicolas.calcium.block;

import net.fabricmc.fabric.api.object.builder.v1.block.entity.FabricBlockEntityTypeBuilder;
import net.fabricmc.fabric.api.object.builder.v1.block.type.BlockSetTypeBuilder;
import net.fabricmc.fabric.api.object.builder.v1.block.type.WoodTypeBuilder;
import net.minecraft.core.Registry;
import net.minecraft.core.cauldron.CauldronInteraction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.util.ColorRGBA;
import net.minecraft.util.valueproviders.ConstantInt;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraft.world.level.material.FlowingFluid;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;
import net.nicolas.calcium.block.custom.*;
import net.nicolas.calcium.sound.ModSoundGroups;

import java.util.function.Function;

public class ModBlocks {

    public static final String MOD_ID = "calcium";

    // ADJACENT REGISTRATIONS

    public static final BlockSetType CHORUS_BLOCK_SET_TYPE = BlockSetTypeBuilder.copyOf(BlockSetType.OAK).soundType(ModSoundGroups.CHORUS_PLANKS).doorOpenSound(ModSoundGroups.CHORUS_DOOR_OPEN).doorCloseSound(ModSoundGroups.CHORUS_DOOR_CLOSE).trapdoorOpenSound(ModSoundGroups.CHORUS_TRAPDOOR_OPEN).trapdoorCloseSound(ModSoundGroups.CHORUS_TRAPDOOR_CLOSE).register(Identifier.fromNamespaceAndPath(MOD_ID, "chorus"));
    public static final WoodType CHORUS_WOOD_TYPE = WoodTypeBuilder.copyOf(WoodType.OAK).soundType(ModSoundGroups.CHORUS_PLANKS).hangingSignSoundType(ModSoundGroups.CHORUS_HANGING_SIGN).fenceGateOpenSound(ModSoundGroups.CHORUS_FENCE_GATE_OPEN).fenceGateCloseSound(ModSoundGroups.CHORUS_FENCE_GATE_OPEN).register(Identifier.fromNamespaceAndPath(MOD_ID, "chorus"), CHORUS_BLOCK_SET_TYPE);
    public static final CauldronInteraction.Dispatcher ECTOPLASM_CAULDRON_BEHAVIOR = new CauldronInteraction.Dispatcher();

    // NATURAL BLOCKS (13, 1)

    public static final Block SILT = register("silt", settings -> new SandBlock(new ColorRGBA(0x766551), settings), BlockBehaviour.Properties.ofFullCopy(Blocks.SAND), true);
    public static final Block SOULSLATE = register("soulslate", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.SOULSLATE).mapColor(MapColor.COLOR_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.4F, 0.4F), true);
    public static final Block NETHERRACK_GLOWSTONE_ORE = register("netherrack_glowstone_ore", GlowstoneOreBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> state.getValue(RedStoneOreBlock.LIT) ? 9 : 0).sound(SoundType.NETHER_ORE).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.4F, 0.4F), true);
    public static final Block MIRESTONE = register("mirestone", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.MIRESTONE).mapColor(MapColor.GLOW_LICHEN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block VERADITE = register("veradite", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block KURODITE = register("kurodite", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block PALLID_MAGNIA = register("pallid_magnia", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.PALLID_MAGNIA).mapColor(MapColor.WOOL).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block UMBRAL_MAGNIA = register("umbral_magnia", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.UMBRAL_MAGNIA).mapColor(MapColor.COLOR_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block END_STONE_SHADOLINE_ORE = register("end_stone_shadoline_ore", settings -> new DropExperienceBlock(ConstantInt.of(0), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE_SHADOLINE_ORE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block MIRESTONE_SHADOLINE_ORE = register("mirestone_shadoline_ore", settings -> new DropExperienceBlock(ConstantInt.of(0), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.MIRESTONE_SHADOLINE_ORE).mapColor(MapColor.GLOW_LICHEN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block RAW_SHADOLINE_BLOCK = register("raw_shadoline_block", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final FlowingFluid ECTOPLASM_STILL = registerFluid("ectoplasm_still", new EctoplasmFluid.Still());
    public static final FlowingFluid ECTOPLASM_FLOWING = registerFluid("ectoplasm_flowing", new EctoplasmFluid.Flowing());
    public static final Block ECTOPLASM = register("ectoplasm", settings -> new LiquidBlock(ECTOPLASM_STILL, settings), BlockBehaviour.Properties.of().mapColor(MapColor.DIAMOND).replaceable().noCollision().strength(100.0F).pushReaction(PushReaction.DESTROY).noLootTable().liquid().lightLevel(state -> 6), false);
    public static final Block ECTOPLASM_CAULDRON = register("ectoplasm_cauldron", settings -> new LayeredCauldronBlock(Biome.Precipitation.NONE, ECTOPLASM_CAULDRON_BEHAVIOR, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.CAULDRON).mapColor(MapColor.METAL).lightLevel(state -> 6), false);

    // PLANT BLOCKS (29, 14)

    public static final Block WILD_WHEAT = register("wild_wheat", DirtPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY), true);
    public static final Block WILD_CARROT = register("wild_carrot", DirtPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY), true);
    public static final Block WILD_POTATO = register("wild_potato", DirtPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY), true);
    public static final Block WILD_BEETROOT = register("wild_beetroot", DirtPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY), true);
    public static final Block BLACK_STINKHORN = register("black_stinkhorn", GenericPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.DEEPSLATE).noCollision().instabreak().sound(SoundType.FUNGUS).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).noOcclusion(), true);
    public static final Block WHITE_STINKHORN = register("white_stinkhorn", GenericPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).noCollision().instabreak().sound(SoundType.FUNGUS).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).noOcclusion(), true);
    public static final Block PONTEDERIA = register("pontederia", (settings) -> new FlowerBlock(MobEffects.WATER_BREATHING, 5.0f, settings), BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY),true);
    public static final Block HIBISCUS = register("hibiscus", (settings) -> new FlowerBlock(MobEffects.BLINDNESS, 5.0f, settings), BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY),true);
    public static final Block POKER = register("poker", (settings) -> new FlowerBlock(MobEffects.NIGHT_VISION, 5.0f, settings), BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY),true);
    public static final Block BUSY_LIZZIE = register("busy_lizzie", BushBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block GOLDENROD = register("goldenrod", TallFlowerBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block BARLEY = register("barley", DoublePlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block SEA_OATS = register("sea_oats", TallDryPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.SAND).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block PAMPAS = register("pampas", TallDryPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.SAND).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block SHORT_ICY_IRIS = register("short_icy_iris", IcyPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.ICE).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block TALL_ICY_IRIS = register("tall_icy_iris", TallIcyPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.ICE).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block CLOVERS = register("clovers", FlowerBedBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.PINK_PETALS).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block EMBER_SPROUTS = register("ember_sprouts", FlatPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.CRIMSON_HYPHAE).replaceable().noCollision().instabreak().sound(SoundType.NETHER_SPROUTS).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY), true);
    public static final Block END_GROWTH = register("end_growth", EndPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.SAND).replaceable().noCollision().instabreak().sound(ModSoundGroups.END_GROWTH).offsetType(BlockBehaviour.OffsetType.XYZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    // Enderweed
    // Enderwort
    public static final Block WISP_SPROUTS = register("wisp_sprouts", WispSproutsBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.GLOW_LICHEN).replaceable().noCollision().instabreak().sound(ModSoundGroups.WISP).lightLevel(state -> 2).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block WISP = register("wisp", EndPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.GLOW_LICHEN).replaceable().noCollision().instabreak().sound(ModSoundGroups.WISP).lightLevel(state -> 4).offsetType(BlockBehaviour.OffsetType.XYZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block FLOWERING_WISP = register("flowering_wisp", TallEndPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.GLOW_LICHEN).replaceable().noCollision().instabreak().sound(ModSoundGroups.FLOWERING_WISP).lightLevel(state -> 6).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    // Aberrant Vines (Body)
    // Aberrant Vines (Head)
    public static final Block CELESTIAL_VINES_BODY = register("celestial_vines_body", CelestialVinesBodyBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_ORANGE).noCollision().instabreak().sound(SoundType.CAVE_VINES).pushReaction(PushReaction.DESTROY).noLootTable(), false);
    public static final Block CELESTIAL_VINES_HEAD = register("celestial_vines_head", CelestialVinesHeadBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.TERRACOTTA_ORANGE).randomTicks().noCollision().instabreak().sound(SoundType.CAVE_VINES).pushReaction(PushReaction.DESTROY).noLootTable(), true);
    public static final Block BLINKVINE_BODY = register("blinkvine_body", BlinkvineBodyBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).noCollision().instabreak().sound(ModSoundGroups.BLINKVINE).pushReaction(PushReaction.DESTROY).noLootTable(), false);
    public static final Block BLINKVINE_HEAD = register("blinkvine_head", BlinkvineHeadBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).randomTicks().noCollision().instabreak().sound(ModSoundGroups.BLINKVINE).pushReaction(PushReaction.DESTROY).noLootTable(), true);
    public static final Block PALLID_MAGNIA_SPROUT = register("pallid_magnia_sprout", MagniaSproutBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.PALLID_MAGNIA).mapColor(MapColor.WOOL).requiresCorrectToolForDrops().pushReaction(PushReaction.DESTROY).strength(2.0F, 6.0F), true);
    public static final Block UMBRAL_MAGNIA_SPROUT = register("umbral_magnia_sprout", MagniaSproutBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.UMBRAL_MAGNIA).mapColor(MapColor.COLOR_GRAY).requiresCorrectToolForDrops().pushReaction(PushReaction.DESTROY).strength(2.0F, 6.0F),  true);

    public static final Block POTTED_PONTEDERIA = register("potted_pontederia", settings -> new FlowerPotBlock(PONTEDERIA, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_HIBISCUS = register("potted_hibiscus", settings -> new FlowerPotBlock(HIBISCUS, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_POKER = register("potted_poker", settings -> new FlowerPotBlock(POKER, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_BLACK_STINKHORN = register("potted_black_stinkhorn", settings -> new FlowerPotBlock(BLACK_STINKHORN, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_WHITE_STINKHORN = register("potted_white_stinkhorn", settings -> new FlowerPotBlock(WHITE_STINKHORN, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_BUSH = register("potted_bush", settings -> new FlowerPotBlock(Blocks.BUSH, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_FIREFLY_BUSH = register("potted_firefly_bush", settings -> new FlowerPotBlock(Blocks.FIREFLY_BUSH, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_BUSY_LIZZIE = register("potted_busy_lizzie", settings -> new FlowerPotBlock(BUSY_LIZZIE, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_PALLID_MAGNIA_SPROUT = register("potted_pallid_magnia_sprout", settings -> new FlowerPotBlock(PALLID_MAGNIA_SPROUT, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_UMBRAL_MAGNIA_SPROUT = register("potted_umbral_magnia_sprout", settings -> new FlowerPotBlock(UMBRAL_MAGNIA_SPROUT, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    // Potted Enderweed
    // Potted Enderwort
    // Potted Wisp

    // WOOD BLOCKS (12, 2)

    public static final Block CHORUS_BLOCK = register("chorus_block", RotatedPillarBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(2.0F, 2.0F), true);
    public static final Block STRIPPED_CHORUS_BLOCK = register("stripped_chorus_block", RotatedPillarBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(2.0F, 2.0F), true);
    public static final Block CHORUS_PLANKS = register("chorus_planks", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F), true);
    public static final Block CHORUS_STAIRS = register("chorus_stairs", settings -> new StairBlock(ModBlocks.CHORUS_PLANKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F), true);
    public static final Block CHORUS_SLAB = register("chorus_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F), true);
    public static final Block CHORUS_FENCE = register("chorus_fence", FenceBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).noOcclusion(), true);
    public static final Block CHORUS_FENCE_GATE = register("chorus_fence_gate", settings -> new FenceGateBlock(CHORUS_WOOD_TYPE, settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).noOcclusion(), true);
    public static final Block CHORUS_DOOR = register("chorus_door", settings -> new DoorBlock(CHORUS_BLOCK_SET_TYPE, settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(3.0F, 3.0F).noOcclusion(), true);
    public static final Block CHORUS_TRAPDOOR = register("chorus_trapdoor", settings -> new TrapDoorBlock(CHORUS_BLOCK_SET_TYPE, settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(3.0F, 3.0F).noOcclusion(), true);
    public static final Block CHORUS_SHELF = register("chorus_shelf", ShelfBlock::new, BlockBehaviour.Properties.of().sound(SoundType.SHELF).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).noOcclusion(), true);
    public static final Block CHORUS_SIGN = register("chorus_sign", settings -> new StandingSignBlock(CHORUS_WOOD_TYPE, settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).noCollision().strength(1.0F, 1.0F).pushReaction(PushReaction.DESTROY), false);
    public static final Block CHORUS_WALL_SIGN = register("chorus_wall_sign", settings -> new WallSignBlock(CHORUS_WOOD_TYPE, settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_PLANKS).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASS).noCollision().strength(1.0F, 1.0F).pushReaction(PushReaction.DESTROY), false);
    public static final Block CHORUS_HANGING_SIGN = register("chorus_hanging_sign", settings -> new CeilingHangingSignBlock(CHORUS_WOOD_TYPE, settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_HANGING_SIGN).mapColor(MapColor.COLOR_MAGENTA).noCollision().strength(1.0F, 1.0F).forceSolidOn().pushReaction(PushReaction.DESTROY), false);
    public static final Block CHORUS_WALL_HANGING_SIGN = register("chorus_wall_hanging_sign", settings -> new WallHangingSignBlock(CHORUS_WOOD_TYPE, settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.CHORUS_HANGING_SIGN).mapColor(MapColor.COLOR_MAGENTA).noCollision().strength(1.0F, 1.0F).forceSolidOn().pushReaction(PushReaction.DESTROY), false);

    // STONE VARIANT BLOCKS (194)

        // Overworld Blocks

        public static final Block POLISHED_STONE = register("polished_stone", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block POLISHED_STONE_STAIRS = register("polished_stone_stairs", settings -> new StairBlock(ModBlocks.POLISHED_STONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block POLISHED_STONE_SLAB = register("polished_stone_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block POLISHED_STONE_WALL = register("polished_stone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_STONE_BRICK_STAIRS = register("cracked_stone_brick_stairs", settings -> new StairBlock(Blocks.CRACKED_STONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_STONE_BRICK_SLAB = register("cracked_stone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_STONE_BRICK_WALL = register("cracked_stone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block SMOOTH_STONE_STAIRS = register("smooth_stone_stairs", settings -> new StairBlock(Blocks.SMOOTH_STONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block SMOOTH_STONE_WALL = register("smooth_stone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block POLISHED_ANDESITE_WALL = register("polished_andesite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block ANDESITE_BRICKS = register("andesite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block ANDESITE_BRICK_STAIRS = register("andesite_brick_stairs", settings -> new StairBlock(ModBlocks.ANDESITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block ANDESITE_BRICK_SLAB = register("andesite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block ANDESITE_BRICK_WALL = register("andesite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_ANDESITE_BRICKS = register("cracked_andesite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_ANDESITE_BRICK_STAIRS = register("cracked_andesite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_ANDESITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_ANDESITE_BRICK_SLAB = register("cracked_andesite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_ANDESITE_BRICK_WALL = register("cracked_andesite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CHISELED_ANDESITE = register("chiseled_andesite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block POLISHED_DIORITE_WALL = register("polished_diorite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block DIORITE_BRICKS = register("diorite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block DIORITE_BRICK_STAIRS = register("diorite_brick_stairs", settings -> new StairBlock(ModBlocks.DIORITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block DIORITE_BRICK_SLAB = register("diorite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block DIORITE_BRICK_WALL = register("diorite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_DIORITE_BRICKS = register("cracked_diorite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_DIORITE_BRICK_STAIRS = register("cracked_diorite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_DIORITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_DIORITE_BRICK_SLAB = register("cracked_diorite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_DIORITE_BRICK_WALL = register("cracked_diorite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CHISELED_DIORITE = register("chiseled_diorite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block POLISHED_GRANITE_WALL = register("polished_granite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block GRANITE_BRICKS = register("granite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block GRANITE_BRICK_STAIRS = register("granite_brick_stairs", settings -> new StairBlock(ModBlocks.GRANITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block GRANITE_BRICK_SLAB = register("granite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block GRANITE_BRICK_WALL = register("granite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_GRANITE_BRICKS = register("cracked_granite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_GRANITE_BRICK_STAIRS = register("cracked_granite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_GRANITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_GRANITE_BRICK_SLAB = register("cracked_granite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_GRANITE_BRICK_WALL = register("cracked_granite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CHISELED_GRANITE = register("chiseled_granite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_DEEPSLATE_BRICK_STAIRS = register("cracked_deepslate_brick_stairs", settings -> new StairBlock(Blocks.CRACKED_DEEPSLATE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
        public static final Block CRACKED_DEEPSLATE_BRICK_SLAB = register("cracked_deepslate_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
        public static final Block CRACKED_DEEPSLATE_BRICK_WALL = register("cracked_deepslate_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
        public static final Block CRACKED_DEEPSLATE_TILE_STAIRS = register("cracked_deepslate_tile_stairs", settings -> new StairBlock(Blocks.CRACKED_DEEPSLATE_TILES.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE_TILES).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
        public static final Block CRACKED_DEEPSLATE_TILE_SLAB = register("cracked_deepslate_tile_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE_TILES).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
        public static final Block CRACKED_DEEPSLATE_TILE_WALL = register("cracked_deepslate_tile_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE_TILES).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
        public static final Block CRACKED_TUFF_BRICKS = register("cracked_tuff_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.TUFF_BRICKS).mapColor(MapColor.TERRACOTTA_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_TUFF_BRICK_STAIRS = register("cracked_tuff_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_TUFF_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.TUFF_BRICKS).mapColor(MapColor.TERRACOTTA_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_TUFF_BRICK_SLAB = register("cracked_tuff_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.TUFF_BRICKS).mapColor(MapColor.TERRACOTTA_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_TUFF_BRICK_WALL = register("cracked_tuff_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.TUFF_BRICKS).mapColor(MapColor.TERRACOTTA_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block POLISHED_DRIPSTONE = register("polished_dripstone", Block::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block POLISHED_DRIPSTONE_STAIRS = register("polished_dripstone_stairs", settings -> new StairBlock(ModBlocks.POLISHED_DRIPSTONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block POLISHED_DRIPSTONE_SLAB = register("polished_dripstone_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block POLISHED_DRIPSTONE_WALL = register("polished_dripstone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block DRIPSTONE_BRICKS = register("dripstone_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block DRIPSTONE_BRICK_STAIRS = register("dripstone_brick_stairs", settings -> new StairBlock(ModBlocks.DRIPSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block DRIPSTONE_BRICK_SLAB = register("dripstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block DRIPSTONE_BRICK_WALL = register("dripstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block CRACKED_DRIPSTONE_BRICKS = register("cracked_dripstone_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block CRACKED_DRIPSTONE_BRICK_STAIRS = register("cracked_dripstone_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_DRIPSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block CRACKED_DRIPSTONE_BRICK_SLAB = register("cracked_dripstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block CRACKED_DRIPSTONE_BRICK_WALL = register("cracked_dripstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block CHISELED_DRIPSTONE = register("chiseled_dripstone", Block::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
        public static final Block POLISHED_CALCITE = register("polished_calcite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block POLISHED_CALCITE_STAIRS = register("polished_calcite_stairs", settings -> new StairBlock(ModBlocks.POLISHED_CALCITE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block POLISHED_CALCITE_SLAB = register("polished_calcite_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block POLISHED_CALCITE_WALL = register("polished_calcite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CALCITE_BRICKS = register("calcite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CALCITE_BRICK_STAIRS = register("calcite_brick_stairs", settings -> new StairBlock(ModBlocks.CALCITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CALCITE_BRICK_SLAB = register("calcite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CALCITE_BRICK_WALL = register("calcite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CRACKED_CALCITE_BRICKS = register("cracked_calcite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CRACKED_CALCITE_BRICK_STAIRS = register("cracked_calcite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_CALCITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CRACKED_CALCITE_BRICK_SLAB = register("cracked_calcite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CRACKED_CALCITE_BRICK_WALL = register("cracked_calcite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CHISELED_CALCITE = register("chiseled_calcite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
        public static final Block CRACKED_CINNABAR_BRICKS = register("cracked_cinnabar_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CINNABAR).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_CINNABAR_BRICK_STAIRS = register("cracked_cinnabar_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_CINNABAR_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.CINNABAR).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_CINNABAR_BRICK_SLAB = register("cracked_cinnabar_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CINNABAR).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_CINNABAR_BRICK_WALL = register("cracked_cinnabar_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CINNABAR).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_SULFUR_BRICKS = register("cracked_sulfur_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.SULFUR).mapColor(MapColor.COLOR_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_SULFUR_BRICK_STAIRS = register("cracked_sulfur_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_SULFUR_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.SULFUR).mapColor(MapColor.COLOR_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_SULFUR_BRICK_SLAB = register("cracked_sulfur_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.SULFUR).mapColor(MapColor.COLOR_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_SULFUR_BRICK_WALL = register("cracked_sulfur_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.SULFUR).mapColor(MapColor.COLOR_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);

        public static final Block POLISHED_PACKED_MUD = register("polished_packed_mud", Block::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
        public static final Block POLISHED_PACKED_MUD_STAIRS = register("polished_packed_mud_stairs", settings -> new StairBlock(ModBlocks.POLISHED_PACKED_MUD.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
        public static final Block POLISHED_PACKED_MUD_SLAB = register("polished_packed_mud_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
        public static final Block POLISHED_PACKED_MUD_WALL = register("polished_packed_mud_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
        public static final Block CRACKED_PACKED_MUD_BRICKS = register("cracked_packed_mud_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.MUD_BRICKS).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
        public static final Block CRACKED_PACKED_MUD_BRICK_STAIRS = register("cracked_packed_mud_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_PACKED_MUD_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.MUD_BRICKS).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
        public static final Block CRACKED_PACKED_MUD_BRICK_SLAB = register("cracked_packed_mud_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.MUD_BRICKS).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
        public static final Block CRACKED_PACKED_MUD_BRICK_WALL = register("cracked_packed_mud_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.MUD_BRICKS).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
        public static final Block CHISELED_PACKED_MUD = register("chiseled_packed_mud", Block::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
        public static final Block POLISHED_SANDSTONE_WALL = register("polished_sandstone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block SANDSTONE_BRICK_STAIRS = register("sandstone_brick_stairs", settings -> new StairBlock(Blocks.CUT_SANDSTONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block SANDSTONE_BRICK_WALL = register("sandstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_SANDSTONE_BRICKS = register("cracked_sandstone_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_SANDSTONE_BRICK_STAIRS = register("cracked_sandstone_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_SANDSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_SANDSTONE_BRICK_SLAB = register("cracked_sandstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_SANDSTONE_BRICK_WALL = register("cracked_sandstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block POLISHED_RED_SANDSTONE_WALL = register("polished_red_sandstone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block RED_SANDSTONE_BRICK_STAIRS = register("red_sandstone_brick_stairs", settings -> new StairBlock(Blocks.CUT_RED_SANDSTONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block RED_SANDSTONE_BRICK_WALL = register("red_sandstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_RED_SANDSTONE_BRICKS = register("cracked_red_sandstone_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_RED_SANDSTONE_BRICK_STAIRS = register("cracked_red_sandstone_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_RED_SANDSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_RED_SANDSTONE_BRICK_SLAB = register("cracked_red_sandstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_RED_SANDSTONE_BRICK_WALL = register("cracked_red_sandstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block PRISMARINE_BRICK_WALL = register("prismarine_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIAMOND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block DARK_PRISMARINE_WALL = register("dark_prismarine_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIAMOND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);

        public static final Block CRACKED_BRICKS = register("cracked_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_BRICK_STAIRS = register("cracked_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_BRICK_SLAB = register("cracked_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_BRICK_WALL = register("cracked_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CHISELED_BRICKS = register("chiseled_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_RESIN_BRICKS = register("cracked_resin_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.RESIN_BRICKS).mapColor(MapColor.TERRACOTTA_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_RESIN_BRICK_STAIRS = register("cracked_resin_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_RESIN_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.RESIN_BRICKS).mapColor(MapColor.TERRACOTTA_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_RESIN_BRICK_SLAB = register("cracked_resin_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.RESIN_BRICKS).mapColor(MapColor.TERRACOTTA_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
        public static final Block CRACKED_RESIN_BRICK_WALL = register("cracked_resin_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.RESIN_BRICKS).mapColor(MapColor.TERRACOTTA_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);

        // Nether Blocks

        public static final Block CRACKED_BLACKSTONE_BRICK_STAIRS = register("cracked_blackstone_brick_stairs", settings -> new StairBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.BLACKSTONE).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BLACKSTONE_BRICK_SLAB = register("cracked_blackstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.BLACKSTONE).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BLACKSTONE_BRICK_WALL = register("cracked_blackstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.BLACKSTONE).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block POLISHED_BASALT = register("polished_basalt", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block POLISHED_BASALT_STAIRS = register("polished_basalt_stairs", settings -> new StairBlock(ModBlocks.POLISHED_BASALT.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block POLISHED_BASALT_SLAB = register("polished_basalt_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block POLISHED_BASALT_WALL = register("polished_basalt_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block BASALT_BRICKS = register("basalt_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block BASALT_BRICK_STAIRS = register("basalt_brick_stairs", settings -> new StairBlock(ModBlocks.BASALT_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block BASALT_BRICK_SLAB = register("basalt_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block BASALT_BRICK_WALL = register("basalt_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BASALT_BRICKS = register("cracked_basalt_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BASALT_BRICK_STAIRS = register("cracked_basalt_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_BASALT_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BASALT_BRICK_SLAB = register("cracked_basalt_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BASALT_BRICK_WALL = register("cracked_basalt_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block BASALT_TILES = register("basalt_tiles", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block BASALT_TILE_STAIRS = register("basalt_tile_stairs", settings -> new StairBlock(ModBlocks.BASALT_TILES.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block BASALT_TILE_SLAB = register("basalt_tile_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block BASALT_TILE_WALL = register("basalt_tile_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BASALT_TILES = register("cracked_basalt_tiles", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BASALT_TILE_STAIRS = register("cracked_basalt_tile_stairs", settings -> new StairBlock(ModBlocks.CRACKED_BASALT_TILES.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BASALT_TILE_SLAB = register("cracked_basalt_tile_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CRACKED_BASALT_TILE_WALL = register("cracked_basalt_tile_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block CHISELED_BASALT = register("chiseled_basalt", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
        public static final Block ENGRAVED_BASALT = register("engraved_basalt", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);

        public static final Block POLISHED_QUARTZ_WALL = register("polished_quartz_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.QUARTZ).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block QUARTZ_BRICK_STAIRS = register("quartz_brick_stairs", settings -> new StairBlock(Blocks.QUARTZ_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.QUARTZ).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block QUARTZ_BRICK_SLAB = register("quartz_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.QUARTZ).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block QUARTZ_BRICK_WALL = register("quartz_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.QUARTZ).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_QUARTZ_BRICKS = register("cracked_quartz_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.QUARTZ).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_QUARTZ_BRICK_STAIRS = register("cracked_quartz_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_QUARTZ_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.QUARTZ).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_QUARTZ_BRICK_SLAB = register("cracked_quartz_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.QUARTZ).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
        public static final Block CRACKED_QUARTZ_BRICK_WALL = register("cracked_quartz_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.QUARTZ).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);

        public static final Block CRACKED_RED_NETHER_BRICKS = register("cracked_red_nether_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_NETHER_BRICK_STAIRS = register("cracked_nether_brick_stairs", settings -> new StairBlock(Blocks.CRACKED_NETHER_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_NETHER_BRICK_SLAB = register("cracked_nether_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_NETHER_BRICK_WALL = register("cracked_nether_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_RED_NETHER_BRICK_STAIRS = register("cracked_red_nether_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_RED_NETHER_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_RED_NETHER_BRICK_SLAB = register("cracked_red_nether_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CRACKED_RED_NETHER_BRICK_WALL = register("cracked_red_nether_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CHISELED_RED_NETHER_BRICKS = register("chiseled_red_nether_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);

        // End Blocks

        public static final Block POLISHED_END_STONE = register("polished_end_stone", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_END_STONE_STAIRS = register("polished_end_stone_stairs", settings -> new StairBlock(ModBlocks.POLISHED_END_STONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_END_STONE_SLAB = register("polished_end_stone_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_END_STONE_WALL = register("polished_end_stone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_END_STONE_BRICKS = register("cracked_end_stone_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_END_STONE_BRICK_STAIRS = register("cracked_end_stone_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_END_STONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_END_STONE_BRICK_SLAB = register("cracked_end_stone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_END_STONE_BRICK_WALL = register("cracked_end_stone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CHISELED_END_STONE = register("chiseled_end_stone", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_VERADITE = register("polished_veradite", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_VERADITE_STAIRS = register("polished_veradite_stairs", settings -> new StairBlock(ModBlocks.POLISHED_VERADITE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_VERADITE_SLAB = register("polished_veradite_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_VERADITE_WALL = register("polished_veradite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block VERADITE_BRICKS = register("veradite_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block VERADITE_BRICK_STAIRS = register("veradite_brick_stairs", settings -> new StairBlock(ModBlocks.VERADITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block VERADITE_BRICK_SLAB = register("veradite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block VERADITE_BRICK_WALL = register("veradite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_VERADITE_BRICKS = register("cracked_veradite_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_VERADITE_BRICK_STAIRS = register("cracked_veradite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_VERADITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_VERADITE_BRICK_SLAB = register("cracked_veradite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_VERADITE_BRICK_WALL = register("cracked_veradite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CHISELED_VERADITE = register("chiseled_veradite", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_KURODITE = register("polished_kurodite", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_KURODITE_STAIRS = register("polished_kurodite_stairs", settings -> new StairBlock(ModBlocks.POLISHED_KURODITE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_KURODITE_SLAB = register("polished_kurodite_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block POLISHED_KURODITE_WALL = register("polished_kurodite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block KURODITE_BRICKS = register("kurodite_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block KURODITE_BRICK_STAIRS = register("kurodite_brick_stairs", settings -> new StairBlock(ModBlocks.KURODITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block KURODITE_BRICK_SLAB = register("kurodite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block KURODITE_BRICK_WALL = register("kurodite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_KURODITE_BRICKS = register("cracked_kurodite_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_KURODITE_BRICK_STAIRS = register("cracked_kurodite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_KURODITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_KURODITE_BRICK_SLAB = register("cracked_kurodite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CRACKED_KURODITE_BRICK_WALL = register("cracked_kurodite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
        public static final Block CHISELED_KURODITE = register("chiseled_kurodite", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);

        public static final Block PURPUR_WALL = register("purpur_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.PURPUR).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
        public static final Block CHISELED_PURPUR = register("chiseled_purpur", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.PURPUR).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);

    // METAL VARIANT BLOCKS (29)

    public static final Block CUT_IRON = register("cut_iron", Block::new, BlockBehaviour.Properties.of().sound(SoundType.IRON).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_IRON_STAIRS = register("cut_iron_stairs", settings -> new StairBlock(ModBlocks.CUT_IRON.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.IRON).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_IRON_SLAB = register("cut_iron_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.IRON).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CHISELED_IRON = register("chiseled_iron", Block::new, BlockBehaviour.Properties.of().sound(SoundType.IRON).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block IRON_GRATE = register("iron_grate", WaterloggedTransparentBlock::new, BlockBehaviour.Properties.of().sound(SoundType.COPPER_GRATE).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0f, 6.0f).noOcclusion(), true);
    public static final Block IRON_BULB = register("iron_bulb", CopperBulbBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> state.getValue(CopperBulbBlock.LIT) ? 15 : 0).sound(SoundType.COPPER_BULB).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0f, 6.0f), true);

    public static final Block CUT_GOLD = register("cut_gold", Block::new, BlockBehaviour.Properties.of().sound(SoundType.METAL).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CUT_GOLD_STAIRS = register("cut_gold_stairs", settings -> new StairBlock(ModBlocks.CUT_GOLD.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.METAL).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CUT_GOLD_SLAB = register("cut_gold_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.METAL).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CHISELED_GOLD = register("chiseled_gold", Block::new, BlockBehaviour.Properties.of().sound(SoundType.METAL).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block GOLD_GRATE = register("gold_grate", WaterloggedTransparentBlock::new, BlockBehaviour.Properties.of().sound(SoundType.COPPER_GRATE).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).noOcclusion().requiresCorrectToolForDrops().strength(3.0f, 6.0f), true);
    public static final Block GOLD_BULB = register("gold_bulb", CopperBulbBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> state.getValue(CopperBulbBlock.LIT) ? 15 : 0).sound(SoundType.COPPER_BULB).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0f, 6.0f), true);
    public static final Block GOLD_DOOR = register("gold_door", settings -> new DoorBlock(BlockSetType.COPPER, settings), BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().noOcclusion().pushReaction(PushReaction.DESTROY).strength(3.0F, 6.0F), true);
    public static final Block GOLD_TRAPDOOR = register("gold_trapdoor", (settings) -> new TrapDoorBlock(BlockSetType.COPPER, settings), BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().noOcclusion().pushReaction(PushReaction.DESTROY).strength(3.0F, 6.0F), true);
    public static final Block GOLD_BARS = register("gold_bars", IronBarsBlock::new, BlockBehaviour.Properties.of().sound(SoundType.METAL).noOcclusion().requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block GOLD_CHAIN = register("gold_chain", ChainBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.GOLD_CHAIN).noOcclusion().forceSolidOn().requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block GOLD_LANTERN = register("gold_lantern", LanternBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> 15).sound(SoundType.LANTERN).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).pushReaction(PushReaction.DESTROY).requiresCorrectToolForDrops().noOcclusion().strength(3.5f, 3.5f), true);

    public static final Block SHADOLINE_BLOCK = register("shadoline_block", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_SHADOLINE = register("cut_shadoline", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_SHADOLINE_STAIRS = register("cut_shadoline_stairs", settings -> new StairBlock(ModBlocks.CUT_SHADOLINE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSoundGroups.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_SHADOLINE_SLAB = register("cut_shadoline_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CHISELED_SHADOLINE = register("chiseled_shadoline", Block::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_GRATE = register("shadoline_grate", WaterloggedTransparentBlock::new, BlockBehaviour.Properties.of().sound(SoundType.COPPER_GRATE).mapColor(MapColor.WARPED_NYLIUM).noOcclusion().requiresCorrectToolForDrops().strength(5.0f, 6.0f), true);
    public static final Block SHADOLINE_BULB = register("shadoline_bulb", CopperBulbBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> state.getValue(CopperBulbBlock.LIT) ? 15 : 0).sound(SoundType.COPPER_BULB).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0f, 6.0f), true);
    public static final Block SHADOLINE_DOOR = register("shadoline_door", settings -> new DoorBlock(BlockSetType.COPPER, settings), BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().noOcclusion().pushReaction(PushReaction.DESTROY).strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_TRAPDOOR = register("shadoline_trapdoor", (settings) -> new TrapDoorBlock(BlockSetType.COPPER, settings), BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().noOcclusion().pushReaction(PushReaction.DESTROY).strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_BARS = register("shadoline_bars", IronBarsBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.SHADOLINE).noOcclusion().requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_CHAIN = register("shadoline_chain", ChainBlock::new, BlockBehaviour.Properties.of().sound(ModSoundGroups.SHADOLINE_CHAIN).noOcclusion().forceSolidOn().requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_LANTERN = register("shadoline_lantern", LanternBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> 15).sound(SoundType.LANTERN).mapColor(MapColor.WARPED_NYLIUM).pushReaction(PushReaction.DESTROY).requiresCorrectToolForDrops().noOcclusion().strength(3.5f, 3.5f), true);

    // DECORATIVE BLOCKS (1)

    public static final Block SOUL_GLASS = register("soul_glass", TransparentBlock::new, BlockBehaviour.Properties.of().sound(SoundType.GLASS).instrument(NoteBlockInstrument.HAT).strength(0.6F, 0.6F).noOcclusion().isValidSpawn(Blocks::never).isRedstoneConductor(Blocks::never).isSuffocating(Blocks::never).isViewBlocking(Blocks::never), true);

    // FUNCTIONAL BLOCKS (6, 17)

    public static final Block OVEN = register("oven", OvenBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.5F, 6.0F), true);
    public static final BlockEntityType<OvenBlockEntity> OVEN_BLOCK_ENTITY = Registry.register(BuiltInRegistries.BLOCK_ENTITY_TYPE, Identifier.fromNamespaceAndPath(MOD_ID, "oven"), FabricBlockEntityTypeBuilder.create(OvenBlockEntity::new, OVEN).build());
    public static final Block MONITOR = register("monitor", MonitorBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CHISELED_BOOKSHELF).mapColor(MapColor.COLOR_BROWN).instrument(NoteBlockInstrument.BASS).strength(2.5F, 2.5F).lightLevel(state -> state.getValue(BlockStateProperties.POWERED) ? 7 : 0), true);
    public static final BlockEntityType<MonitorBlockEntity> MONITOR_BLOCK_ENTITY = Registry.register(BuiltInRegistries.BLOCK_ENTITY_TYPE, Identifier.fromNamespaceAndPath(MOD_ID, "monitor"), FabricBlockEntityTypeBuilder.create(MonitorBlockEntity::new, MONITOR).build());
    public static final Block VIEWFINDER = register("viewfinder", ViewfinderBlock::new, BlockBehaviour.Properties.of().sound(SoundType.METAL).mapColor(MapColor.COLOR_LIGHT_GRAY).instrument(NoteBlockInstrument.IRON_XYLOPHONE).strength(3.5F, 3.5F).noOcclusion(), true);
    public static final BlockEntityType<ViewfinderBlockEntity> VIEWFINDER_BLOCK_ENTITY = Registry.register(BuiltInRegistries.BLOCK_ENTITY_TYPE, Identifier.fromNamespaceAndPath(MOD_ID, "viewfinder"), FabricBlockEntityTypeBuilder.create(ViewfinderBlockEntity::new, VIEWFINDER).build());

    public static final Block CHOCOLATE_CAKE = register("chocolate_cake", CakeBlock::new, BlockBehaviour.Properties.ofFullCopy(Blocks.CAKE), false);
    public static final Block CANDLE_CHOCOLATE_CAKE = register("candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.CANDLE, p), BlockBehaviour.Properties.ofLegacyCopy(CHOCOLATE_CAKE).lightLevel(state -> state.getValue(BlockStateProperties.LIT) ? 3 : 0), false);
    public static final Block WHITE_CANDLE_CHOCOLATE_CAKE = register("white_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.WHITE), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block ORANGE_CANDLE_CHOCOLATE_CAKE = register("orange_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.ORANGE), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block MAGENTA_CANDLE_CHOCOLATE_CAKE = register("magenta_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.MAGENTA), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block LIGHT_BLUE_CANDLE_CHOCOLATE_CAKE = register("light_blue_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.LIGHT_BLUE), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block YELLOW_CANDLE_CHOCOLATE_CAKE = register("yellow_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.YELLOW), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block LIME_CANDLE_CHOCOLATE_CAKE = register("lime_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.LIME), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block PINK_CANDLE_CHOCOLATE_CAKE = register("pink_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.PINK), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block GRAY_CANDLE_CHOCOLATE_CAKE = register("gray_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.GRAY), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block LIGHT_GRAY_CANDLE_CHOCOLATE_CAKE = register("light_gray_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.LIGHT_GRAY), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block CYAN_CANDLE_CHOCOLATE_CAKE = register("cyan_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.CYAN), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block PURPLE_CANDLE_CHOCOLATE_CAKE = register("purple_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.PURPLE), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block BLUE_CANDLE_CHOCOLATE_CAKE = register("blue_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.BLUE), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block BROWN_CANDLE_CHOCOLATE_CAKE = register("brown_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.BROWN), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block GREEN_CANDLE_CHOCOLATE_CAKE = register("green_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.GREEN), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block RED_CANDLE_CHOCOLATE_CAKE = register("red_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.RED), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block BLACK_CANDLE_CHOCOLATE_CAKE = register("black_candle_chocolate_cake", p -> new CandleChocolateCakeBlock(Blocks.DYED_CANDLE.pick(DyeColor.BLACK), p), BlockBehaviour.Properties.ofLegacyCopy(CANDLE_CHOCOLATE_CAKE), false);
    public static final Block PUMPKIN_CAKE_ROLL = register("pumpkin_cake_roll", CakeRollBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_ORANGE).forceSolidOn().sound(ModSoundGroups.CAKE_ROLL).strength(0.5F).pushReaction(PushReaction.DESTROY).noLootTable(), false);
    public static final Block CHORUS_CAKE_ROLL = register("chorus_cake_roll", ChorusCakeRollBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_MAGENTA).forceSolidOn().sound(ModSoundGroups.CAKE_ROLL).strength(0.5F).pushReaction(PushReaction.DESTROY).noLootTable(), false);

    public static void initialize() {}

    private static Block register(String name, Function<BlockBehaviour.Properties, Block> blockFactory, BlockBehaviour.Properties settings, boolean registerItem) {

        ResourceKey<Block> blockKey = keyOfBlock(name);
        Block block = blockFactory.apply(settings.setId(blockKey));

        if (registerItem) {ResourceKey<Item> itemKey = keyOfItem(name);BlockItem blockItem = new BlockItem(block, new Item.Properties().setId(itemKey).useBlockDescriptionPrefix());Registry.register(BuiltInRegistries.ITEM, itemKey, blockItem);
        }

        return Registry.register(BuiltInRegistries.BLOCK, blockKey, block);

    }

    private static FlowingFluid registerFluid(String name, FlowingFluid fluid) {
        return Registry.register(BuiltInRegistries.FLUID, Identifier.fromNamespaceAndPath(MOD_ID, name), fluid);
    }

    private static ResourceKey<Block> keyOfBlock(String name) {
        return ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(MOD_ID, name));
    }

    private static ResourceKey<Item> keyOfItem(String name) {
        return ResourceKey.create(Registries.ITEM, Identifier.fromNamespaceAndPath(MOD_ID, name));
    }

}