package net.nicolas.calcium.block;

import net.fabricmc.fabric.api.creativetab.v1.CreativeModeTabEvents;
import net.minecraft.core.Registry;
import net.minecraft.core.cauldron.CauldronInteraction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.util.ColorRGBA;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;
import net.nicolas.calcium.block.custom.*;
import net.nicolas.calcium.fluid.ModFluids;
import net.nicolas.calcium.sound.ModSounds;

import java.util.function.Function;

public class ModBlocks {

    public static final String MOD_ID = "calcium";

    // NATURAL BLOCKS (7)

    public static final Block SILT = register("silt", settings -> new SandBlock(new ColorRGBA(0x766551), settings), BlockBehaviour.Properties.ofFullCopy(Blocks.SAND), true);
    public static final Block SOULSLATE = register("soulslate", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.SOULSLATE).mapColor(MapColor.COLOR_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.4F, 0.4F), true);
    public static final Block NETHERRACK_GLOWSTONE_ORE = register("netherrack_glowstone_ore", GlowstoneOreBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> state.getValue(RedStoneOreBlock.LIT) ? 9 : 0).sound(SoundType.NETHER_ORE).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 3.0F), true);
    public static final Block KURODITE = register("kurodite", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block VERADITE = register("veradite", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block PALLID_MAGNIA = register("pallid_magnia", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.PALLID_MAGNIA).mapColor(MapColor.WOOL).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block UMBRAL_MAGNIA = register("umbral_magnia", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.UMBRAL_MAGNIA).mapColor(MapColor.COLOR_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block RAW_SHADOLINE_BLOCK = register("raw_shadoline_block", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);

    // NATURAL FLUIDS (1, 1)

    public static final Block ECTOPLASM = register("ectoplasm", settings -> new LiquidBlock(ModFluids.ECTOPLASM_STILL, settings), BlockBehaviour.Properties.of().mapColor(MapColor.DIAMOND).replaceable().noCollision().strength(100.0F).pushReaction(PushReaction.DESTROY).noLootTable().liquid().lightLevel(state -> 6), false);
    public static final CauldronInteraction.Dispatcher ECTOPLASM_CAULDRON_BEHAVIOR = new CauldronInteraction.Dispatcher();
    public static final Block ECTOPLASM_CAULDRON = register("ectoplasm_cauldron", settings -> new LayeredCauldronBlock(Biome.Precipitation.NONE, ECTOPLASM_CAULDRON_BEHAVIOR, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.CAULDRON).mapColor(MapColor.METAL).lightLevel(state -> 6), false);

    // PLANT BLOCKS (18, 5)

    public static final Block WILD_WHEAT = register("wild_wheat", DirtPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY), true);
    public static final Block WILD_CARROT = register("wild_carrot", DirtPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY), true);
    public static final Block WILD_POTATO = register("wild_potato", DirtPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY), true);
    public static final Block WILD_BEETROOT = register("wild_beetroot", DirtPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY), true);
    public static final Block PONTEDERIA = register("pontederia", (settings) -> new FlowerBlock(MobEffects.WATER_BREATHING, 5.0f, settings), BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY),true);
    public static final Block HIBISCUS = register("hibiscus", (settings) -> new FlowerBlock(MobEffects.BLINDNESS, 5.0f, settings), BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY),true);
    public static final Block POKER = register("poker", (settings) -> new FlowerBlock(MobEffects.NIGHT_VISION, 5.0f, settings), BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY),true);
    public static final Block BLACK_STINKHORN = register("black_stinkhorn", GenericPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.DEEPSLATE).noCollision().instabreak().sound(SoundType.FUNGUS).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).noOcclusion(), true);
    public static final Block WHITE_STINKHORN = register("white_stinkhorn", GenericPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).noCollision().instabreak().sound(SoundType.FUNGUS).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).noOcclusion(), true);
    public static final Block BUSY_LIZZIE = register("busy_lizzie", BushBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block GOLDENROD = register("goldenrod", TallFlowerBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block BARLEY = register("barley", DoublePlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block SEA_OATS = register("sea_oats", TallDryPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.SAND).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block PAMPAS = register("pampas", TallDryPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.SAND).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block ICY_IRIS = register("icy_iris", IcyPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.ICE).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block TALL_ICY_IRIS = register("tall_icy_iris", TallIcyPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.ICE).replaceable().noCollision().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block CLOVERS = register("clovers", FlowerBedBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).replaceable().noCollision().instabreak().sound(SoundType.PINK_PETALS).pushReaction(PushReaction.DESTROY).ignitedByLava(), true);
    public static final Block EMBER_SPROUTS = register("ember_sprouts", FlatPlantBlock::new, BlockBehaviour.Properties.of().mapColor(MapColor.CRIMSON_HYPHAE).replaceable().noCollision().instabreak().sound(SoundType.NETHER_SPROUTS).offsetType(BlockBehaviour.OffsetType.XZ).pushReaction(PushReaction.DESTROY), true);
    public static final Block POTTED_PONTEDERIA = register("potted_pontederia", settings -> new FlowerPotBlock(PONTEDERIA, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_HIBISCUS = register("potted_hibiscus", settings -> new FlowerPotBlock(HIBISCUS, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_POKER = register("potted_poker", settings -> new FlowerPotBlock(POKER, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_BLACK_STINKHORN = register("potted_black_stinkhorn", settings -> new FlowerPotBlock(BLACK_STINKHORN, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_WHITE_STINKHORN = register("potted_white_stinkhorn", settings -> new FlowerPotBlock(WHITE_STINKHORN, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_BUSH = register("potted_bush", settings -> new FlowerPotBlock(Blocks.BUSH, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_FIREFLY_BUSH = register("potted_firefly_bush", settings -> new FlowerPotBlock(Blocks.FIREFLY_BUSH, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);
    public static final Block POTTED_BUSY_LIZZIE = register("potted_busy_lizzie", settings -> new FlowerPotBlock(BUSY_LIZZIE, settings), BlockBehaviour.Properties.ofFullCopy(Blocks.FLOWER_POT), false);


    // STONE VARIANT BLOCKS (194)

    public static final Block POLISHED_STONE = register("polished_stone", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block POLISHED_STONE_STAIRS = register("polished_stone_stairs", settings -> new StairBlock(ModBlocks.POLISHED_STONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block POLISHED_STONE_SLAB = register("polished_stone_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block POLISHED_STONE_WALL = register("polished_stone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_STONE_BRICK_STAIRS = register("cracked_stone_brick_stairs", settings -> new StairBlock(Blocks.CRACKED_STONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_STONE_BRICK_SLAB = register("cracked_stone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_STONE_BRICK_WALL = register("cracked_stone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block SMOOTH_STONE_STAIRS = register("smooth_stone_stairs", settings -> new StairBlock(Blocks.SMOOTH_STONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block SMOOTH_STONE_WALL = register("smooth_stone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block POLISHED_ANDESITE_WALL = register("polished_andesite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block ANDESITE_BRICKS = register("andesite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block ANDESITE_BRICK_STAIRS = register("andesite_brick_stairs", settings -> new StairBlock(ModBlocks.ANDESITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block ANDESITE_BRICK_SLAB = register("andesite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block ANDESITE_BRICK_WALL = register("andesite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_ANDESITE_BRICKS = register("cracked_andesite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_ANDESITE_BRICK_STAIRS = register("cracked_andesite_brick_stairs", settings -> new StairBlock(ModBlocks.ANDESITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_ANDESITE_BRICK_SLAB = register("cracked_andesite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_ANDESITE_BRICK_WALL = register("cracked_andesite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CHISELED_ANDESITE = register("chiseled_andesite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block POLISHED_DIORITE_WALL = register("polished_diorite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block DIORITE_BRICKS = register("diorite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block DIORITE_BRICK_STAIRS = register("diorite_brick_stairs", settings -> new StairBlock(ModBlocks.DIORITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block DIORITE_BRICK_SLAB = register("diorite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block DIORITE_BRICK_WALL = register("diorite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_DIORITE_BRICKS = register("cracked_diorite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_DIORITE_BRICK_STAIRS = register("cracked_diorite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_DIORITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_DIORITE_BRICK_SLAB = register("cracked_diorite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_DIORITE_BRICK_WALL = register("cracked_diorite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CHISELED_DIORITE = register("chiseled_diorite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block POLISHED_GRANITE_WALL = register("polished_granite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block GRANITE_BRICKS = register("granite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block GRANITE_BRICK_STAIRS = register("granite_brick_stairs", settings -> new StairBlock(ModBlocks.GRANITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block GRANITE_BRICK_SLAB = register("granite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block GRANITE_BRICK_WALL = register("granite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_GRANITE_BRICKS = register("cracked_granite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_GRANITE_BRICK_STAIRS = register("cracked_granite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_GRANITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_GRANITE_BRICK_SLAB = register("cracked_granite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_GRANITE_BRICK_WALL = register("cracked_granite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CHISELED_GRANITE = register("chiseled_granite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_DEEPSLATE_BRICK_STAIRS = register("cracked_deepslate_brick_stairs", settings -> new StairBlock(Blocks.CRACKED_DEEPSLATE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CRACKED_DEEPSLATE_BRICK_SLAB = register("cracked_deepslate_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CRACKED_DEEPSLATE_BRICK_WALL = register("cracked_deepslate_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CRACKED_DEEPSLATE_TILE_STAIRS = register("cracked_deepslate_tile_stairs", settings -> new StairBlock(Blocks.CRACKED_DEEPSLATE_TILES.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE_TILES).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CRACKED_DEEPSLATE_TILE_SLAB = register("cracked_deepslate_tile_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE_TILES).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CRACKED_DEEPSLATE_TILE_WALL = register("cracked_deepslate_tile_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DEEPSLATE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CRACKED_TUFF_BRICKS = register("cracked_tuff_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.TUFF_BRICKS).mapColor(MapColor.TERRACOTTA_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_TUFF_BRICK_STAIRS = register("cracked_tuff_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_TUFF_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.TUFF_BRICKS).mapColor(MapColor.TERRACOTTA_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_TUFF_BRICK_SLAB = register("cracked_tuff_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.TUFF_BRICKS).mapColor(MapColor.TERRACOTTA_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_TUFF_BRICK_WALL = register("cracked_tuff_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.TUFF_BRICKS).mapColor(MapColor.TERRACOTTA_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block POLISHED_DRIPSTONE = register("polished_dripstone", Block::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block POLISHED_DRIPSTONE_STAIRS = register("polished_dripstone_stairs", settings -> new StairBlock(ModBlocks.POLISHED_DRIPSTONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block POLISHED_DRIPSTONE_SLAB = register("polished_dripstone_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block POLISHED_DRIPSTONE_WALL = register("polished_dripstone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block DRIPSTONE_BRICKS = register("dripstone_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block DRIPSTONE_BRICK_STAIRS = register("dripstone_brick_stairs", settings -> new StairBlock(ModBlocks.DRIPSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block DRIPSTONE_BRICK_SLAB = register("dripstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block DRIPSTONE_BRICK_WALL = register("dripstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block CRACKED_DRIPSTONE_BRICKS = register("cracked_dripstone_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block CRACKED_DRIPSTONE_BRICK_STAIRS = register("cracked_dripstone_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_DRIPSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block CRACKED_DRIPSTONE_BRICK_SLAB = register("cracked_dripstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block CRACKED_DRIPSTONE_BRICK_WALL = register("cracked_dripstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block CHISELED_DRIPSTONE = register("chiseled_dripstone", Block::new, BlockBehaviour.Properties.of().sound(SoundType.DRIPSTONE_BLOCK).mapColor(MapColor.TERRACOTTA_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 1.0F), true);
    public static final Block CRACKED_CINNABAR_BRICKS = register("cracked_cinnabar_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CINNABAR).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_CINNABAR_BRICK_STAIRS = register("cracked_cinnabar_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_CINNABAR_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.CINNABAR).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_CINNABAR_BRICK_SLAB = register("cracked_cinnabar_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CINNABAR).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_CINNABAR_BRICK_WALL = register("cracked_cinnabar_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CINNABAR).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_SULFUR_BRICKS = register("cracked_sulfur_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.SULFUR).mapColor(MapColor.COLOR_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_SULFUR_BRICK_STAIRS = register("cracked_sulfur_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_SULFUR_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.SULFUR).mapColor(MapColor.COLOR_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_SULFUR_BRICK_SLAB = register("cracked_sulfur_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.SULFUR).mapColor(MapColor.COLOR_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_SULFUR_BRICK_WALL = register("cracked_sulfur_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.SULFUR).mapColor(MapColor.COLOR_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block POLISHED_CALCITE = register("polished_calcite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block POLISHED_CALCITE_STAIRS = register("polished_calcite_stairs", settings -> new StairBlock(ModBlocks.POLISHED_CALCITE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block POLISHED_CALCITE_SLAB = register("polished_calcite_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block POLISHED_CALCITE_WALL = register("polished_calcite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block CALCITE_BRICKS = register("calcite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block CALCITE_BRICK_STAIRS = register("calcite_brick_stairs", settings -> new StairBlock(ModBlocks.CALCITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block CALCITE_BRICK_SLAB = register("calcite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block CALCITE_BRICK_WALL = register("calcite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block CRACKED_CALCITE_BRICKS = register("cracked_calcite_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block CRACKED_CALCITE_BRICK_STAIRS = register("cracked_calcite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_CALCITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block CRACKED_CALCITE_BRICK_SLAB = register("cracked_calcite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block CRACKED_CALCITE_BRICK_WALL = register("cracked_calcite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block CHISELED_CALCITE = register("chiseled_calcite", Block::new, BlockBehaviour.Properties.of().sound(SoundType.CALCITE).mapColor(MapColor.TERRACOTTA_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.75F, 0.75F), true);
    public static final Block POLISHED_SANDSTONE_WALL = register("polished_sandstone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block SANDSTONE_BRICK_STAIRS = register("sandstone_brick_stairs", settings -> new StairBlock(Blocks.CUT_SANDSTONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block SANDSTONE_BRICK_WALL = register("sandstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_SANDSTONE_BRICKS = register("cracked_sandstone_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_SANDSTONE_BRICK_STAIRS = register("cracked_sandstone_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_SANDSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_SANDSTONE_BRICK_SLAB = register("cracked_sandstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_SANDSTONE_BRICK_WALL = register("cracked_sandstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block POLISHED_RED_SANDSTONE_WALL = register("polished_red_sandstone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block RED_SANDSTONE_BRICK_STAIRS = register("red_sandstone_brick_stairs", settings -> new StairBlock(Blocks.CUT_RED_SANDSTONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block RED_SANDSTONE_BRICK_WALL = register("red_sandstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_RED_SANDSTONE_BRICKS = register("cracked_red_sandstone_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_RED_SANDSTONE_BRICK_STAIRS = register("cracked_red_sandstone_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_RED_SANDSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_RED_SANDSTONE_BRICK_SLAB = register("cracked_red_sandstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_RED_SANDSTONE_BRICK_WALL = register("cracked_red_sandstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block PRISMARINE_BRICK_WALL = register("prismarine_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIAMOND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block DARK_PRISMARINE_WALL = register("dark_prismarine_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.DIAMOND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_BLACKSTONE_BRICK_STAIRS = register("cracked_blackstone_brick_stairs", settings -> new StairBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BLACKSTONE_BRICK_SLAB = register("cracked_blackstone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BLACKSTONE_BRICK_WALL = register("cracked_blackstone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block POLISHED_BASALT = register("polished_basalt", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block POLISHED_BASALT_STAIRS = register("polished_basalt_stairs", settings -> new StairBlock(ModBlocks.POLISHED_BASALT.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block POLISHED_BASALT_SLAB = register("polished_basalt_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block POLISHED_BASALT_WALL = register("polished_basalt_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block BASALT_BRICKS = register("basalt_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block BASALT_BRICK_STAIRS = register("basalt_brick_stairs", settings -> new StairBlock(ModBlocks.BASALT_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block BASALT_BRICK_SLAB = register("basalt_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block BASALT_BRICK_WALL = register("basalt_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BASALT_BRICKS = register("cracked_basalt_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BASALT_BRICK_STAIRS = register("cracked_basalt_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_BASALT_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BASALT_BRICK_SLAB = register("cracked_basalt_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BASALT_BRICK_WALL = register("cracked_basalt_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block BASALT_TILES = register("basalt_tiles", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block BASALT_TILE_STAIRS = register("basalt_tile_stairs", settings -> new StairBlock(ModBlocks.BASALT_TILES.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block BASALT_TILE_SLAB = register("basalt_tile_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block BASALT_TILE_WALL = register("basalt_tile_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BASALT_TILES = register("cracked_basalt_tiles", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BASALT_TILE_STAIRS = register("cracked_basalt_tile_stairs", settings -> new StairBlock(ModBlocks.CRACKED_BASALT_TILES.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BASALT_TILE_SLAB = register("cracked_basalt_tile_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_BASALT_TILE_WALL = register("cracked_basalt_tile_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CHISELED_BASALT = register("chiseled_basalt", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block ENGRAVED_BASALT = register("engraved_basalt", Block::new, BlockBehaviour.Properties.of().sound(SoundType.BASALT).mapColor(MapColor.COLOR_BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block POLISHED_QUARTZ_WALL = register("polished_quartz_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block QUARTZ_BRICK_STAIRS = register("quartz_brick_stairs", settings -> new StairBlock(Blocks.QUARTZ_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block QUARTZ_BRICK_SLAB = register("quartz_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block QUARTZ_BRICK_WALL = register("quartz_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_QUARTZ_BRICKS = register("cracked_quartz_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_QUARTZ_BRICK_STAIRS = register("cracked_quartz_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_QUARTZ_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_QUARTZ_BRICK_SLAB = register("cracked_quartz_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_QUARTZ_BRICK_WALL = register("cracked_quartz_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.QUARTZ).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F, 0.8F), true);
    public static final Block CRACKED_BRICKS = register("cracked_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_BRICK_STAIRS = register("cracked_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_BRICK_SLAB = register("cracked_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_BRICK_WALL = register("cracked_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.COLOR_RED).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_RED_NETHER_BRICKS = register("cracked_red_nether_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.25F, 4.2F), true);
    public static final Block CRACKED_NETHER_BRICK_STAIRS = register("cracked_nether_brick_stairs", settings -> new StairBlock(Blocks.CRACKED_NETHER_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_NETHER_BRICK_SLAB = register("cracked_nether_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_NETHER_BRICK_WALL = register("cracked_nether_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_RED_NETHER_BRICK_STAIRS = register("cracked_red_nether_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_RED_NETHER_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_RED_NETHER_BRICK_SLAB = register("cracked_red_nether_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_RED_NETHER_BRICK_WALL = register("cracked_red_nether_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CHISELED_RED_NETHER_BRICKS = register("chiseled_red_nether_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS).mapColor(MapColor.NETHER).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CRACKED_RESIN_BRICKS = register("cracked_resin_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.RESIN_BRICKS).mapColor(MapColor.TERRACOTTA_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_RESIN_BRICK_STAIRS = register("cracked_resin_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_RESIN_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.RESIN_BRICKS).mapColor(MapColor.TERRACOTTA_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_RESIN_BRICK_SLAB = register("cracked_resin_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.RESIN_BRICKS).mapColor(MapColor.TERRACOTTA_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block CRACKED_RESIN_BRICK_WALL = register("cracked_resin_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.RESIN_BRICKS).mapColor(MapColor.TERRACOTTA_ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 6.0F), true);
    public static final Block POLISHED_PACKED_MUD = register("polished_packed_mud", Block::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
    public static final Block POLISHED_PACKED_MUD_STAIRS = register("polished_packed_mud_stairs", settings -> new StairBlock(ModBlocks.POLISHED_PACKED_MUD.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
    public static final Block POLISHED_PACKED_MUD_SLAB = register("polished_packed_mud_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
    public static final Block POLISHED_PACKED_MUD_WALL = register("polished_packed_mud_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
    public static final Block CRACKED_PACKED_MUD_BRICKS = register("cracked_packed_mud_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
    public static final Block CRACKED_PACKED_MUD_BRICK_STAIRS = register("cracked_packed_mud_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_PACKED_MUD_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
    public static final Block CRACKED_PACKED_MUD_BRICK_SLAB = register("cracked_packed_mud_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
    public static final Block CRACKED_PACKED_MUD_BRICK_WALL = register("cracked_packed_mud_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
    public static final Block CHISELED_PACKED_MUD = register("chiseled_packed_mud", Block::new, BlockBehaviour.Properties.of().sound(SoundType.PACKED_MUD).mapColor(MapColor.DIRT).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(1.5F, 3.0F), true);
    public static final Block POLISHED_END_STONE = register("polished_end_stone", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_END_STONE_STAIRS = register("polished_end_stone_stairs", settings -> new StairBlock(ModBlocks.POLISHED_END_STONE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSounds.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_END_STONE_SLAB = register("polished_end_stone_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_END_STONE_WALL = register("polished_end_stone_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_END_STONE_BRICKS = register("cracked_end_stone_bricks", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_END_STONE_BRICK_STAIRS = register("cracked_end_stone_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_END_STONE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_END_STONE_BRICK_SLAB = register("cracked_end_stone_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_END_STONE_BRICK_WALL = register("cracked_end_stone_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CHISELED_END_STONE = register("chiseled_end_stone", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.END_STONE).mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_KURODITE = register("polished_kurodite", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_KURODITE_STAIRS = register("polished_kurodite_stairs", settings -> new StairBlock(ModBlocks.POLISHED_KURODITE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSounds.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_KURODITE_SLAB = register("polished_kurodite_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_KURODITE_WALL = register("polished_kurodite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block KURODITE_BRICKS = register("kurodite_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block KURODITE_BRICK_STAIRS = register("kurodite_brick_stairs", settings -> new StairBlock(ModBlocks.KURODITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSounds.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block KURODITE_BRICK_SLAB = register("kurodite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block KURODITE_BRICK_WALL = register("kurodite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_KURODITE_BRICKS = register("cracked_kurodite_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_KURODITE_BRICK_STAIRS = register("cracked_kurodite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_KURODITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSounds.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_KURODITE_BRICK_SLAB = register("cracked_kurodite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_KURODITE_BRICK_WALL = register("cracked_kurodite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CHISELED_KURODITE = register("chiseled_kurodite", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.KURODITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_VERADITE = register("polished_veradite", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_VERADITE_STAIRS = register("polished_veradite_stairs", settings -> new StairBlock(ModBlocks.POLISHED_VERADITE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSounds.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_VERADITE_SLAB = register("polished_veradite_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block POLISHED_VERADITE_WALL = register("polished_veradite_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block VERADITE_BRICKS = register("veradite_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block VERADITE_BRICK_STAIRS = register("veradite_brick_stairs", settings -> new StairBlock(ModBlocks.VERADITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSounds.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block VERADITE_BRICK_SLAB = register("veradite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block VERADITE_BRICK_WALL = register("veradite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_VERADITE_BRICKS = register("cracked_veradite_bricks", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_VERADITE_BRICK_STAIRS = register("cracked_veradite_brick_stairs", settings -> new StairBlock(ModBlocks.CRACKED_VERADITE_BRICKS.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSounds.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_VERADITE_BRICK_SLAB = register("cracked_veradite_brick_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CRACKED_VERADITE_BRICK_WALL = register("cracked_veradite_brick_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE_BRICKS).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block CHISELED_VERADITE = register("chiseled_veradite", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.VERADITE).mapColor(MapColor.DEEPSLATE).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(3.0F, 9.0F), true);
    public static final Block PURPUR_WALL = register("purpur_wall", WallBlock::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);
    public static final Block CHISELED_PURPUR = register("chiseled_purpur", Block::new, BlockBehaviour.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_MAGENTA).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(2.0F, 6.0F), true);

    // METAL VARIANT BLOCKS (30)

    public static final Block CUT_IRON = register("cut_iron", Block::new, BlockBehaviour.Properties.of().sound(SoundType.IRON).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_IRON_STAIRS = register("cut_iron_stairs", settings -> new StairBlock(ModBlocks.CUT_IRON.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.IRON).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_IRON_SLAB = register("cut_iron_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.IRON).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CHISELED_IRON = register("chiseled_iron", Block::new, BlockBehaviour.Properties.of().sound(SoundType.IRON).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block IRON_GRATE = register("iron_grate", WaterloggedTransparentBlock::new, BlockBehaviour.Properties.of().sound(SoundType.COPPER_GRATE).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0f, 6.0f).noOcclusion(), true);
    public static final Block IRON_BULB = register("iron_bulb", CopperBulbBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> state.getValue(CopperBulbBlock.LIT) ? 15 : 0).sound(SoundType.COPPER_BULB).mapColor(MapColor.METAL).instrument(NoteBlockInstrument.IRON_XYLOPHONE).requiresCorrectToolForDrops().strength(5.0f, 6.0f), true);

    public static final Block CUT_GOLD = register("cut_gold", Block::new, BlockBehaviour.Properties.of().sound(SoundType.METAL).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CUT_GOLD_STAIRS = register("cut_gold_stairs", settings -> new StairBlock(ModBlocks.CUT_GOLD.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(SoundType.METAL).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CUT_GOLD_SLAB = register("cut_gold_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(SoundType.METAL).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block CHISELED_GOLD = register("chiseled_gold", Block::new, BlockBehaviour.Properties.of().sound(SoundType.METAL).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block GOLD_GRATE = register("gold_grate", WaterloggedTransparentBlock::new, BlockBehaviour.Properties.of().sound(SoundType.COPPER_GRATE).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).noOcclusion().requiresCorrectToolForDrops().strength(3.0f, 6.0f), true);
    public static final Block GOLD_BULB = register("gold_bulb", CopperBulbBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> state.getValue(CopperBulbBlock.LIT) ? 15 : 0).sound(SoundType.COPPER_BULB).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().strength(3.0f, 6.0f), true);
    public static final Block GOLD_DOOR = register("gold_door", settings -> new DoorBlock(BlockSetType.COPPER, settings), BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().noOcclusion().pushReaction(PushReaction.DESTROY).strength(3.0F, 6.0F), true);
    public static final Block GOLD_TRAPDOOR = register("gold_trapdoor", (settings) -> new TrapDoorBlock(BlockSetType.COPPER, settings), BlockBehaviour.Properties.of().mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).requiresCorrectToolForDrops().noOcclusion().pushReaction(PushReaction.DESTROY).strength(3.0F, 6.0F), true);
    public static final Block GOLD_BARS = register("gold_bars", IronBarsBlock::new, BlockBehaviour.Properties.of().sound(SoundType.METAL).noOcclusion().requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block GOLD_CHAIN = register("gold_chain", ChainBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CHAIN).noOcclusion().forceSolidOn().requiresCorrectToolForDrops().strength(3.0F, 6.0F), true);
    public static final Block GOLD_LANTERN = register("gold_lantern", LanternBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> 15).sound(SoundType.LANTERN).mapColor(MapColor.GOLD).instrument(NoteBlockInstrument.BELL).pushReaction(PushReaction.DESTROY).requiresCorrectToolForDrops().noOcclusion().strength(3.5f, 3.5f), true);

    public static final Block SHADOLINE_BLOCK = register("shadoline_block", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_SHADOLINE = register("cut_shadoline", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_SHADOLINE_STAIRS = register("cut_shadoline_stairs", settings -> new StairBlock(ModBlocks.CUT_SHADOLINE.defaultBlockState(), settings), BlockBehaviour.Properties.of().sound(ModSounds.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CUT_SHADOLINE_SLAB = register("cut_shadoline_slab", SlabBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block CHISELED_SHADOLINE = register("chiseled_shadoline", Block::new, BlockBehaviour.Properties.of().sound(ModSounds.SHADOLINE).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_GRATE = register("shadoline_grate", WaterloggedTransparentBlock::new, BlockBehaviour.Properties.of().sound(SoundType.COPPER_GRATE).mapColor(MapColor.WARPED_NYLIUM).noOcclusion().requiresCorrectToolForDrops().strength(5.0f, 6.0f), true);
    public static final Block SHADOLINE_BULB = register("shadoline_bulb", CopperBulbBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> state.getValue(CopperBulbBlock.LIT) ? 15 : 0).sound(SoundType.COPPER_BULB).mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(5.0f, 6.0f), true);
    public static final Block SHADOLINE_DOOR = register("shadoline_door", settings -> new DoorBlock(BlockSetType.COPPER, settings), BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().noOcclusion().pushReaction(PushReaction.DESTROY).strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_TRAPDOOR = register("shadoline_trapdoor", (settings) -> new TrapDoorBlock(BlockSetType.COPPER, settings), BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_NYLIUM).requiresCorrectToolForDrops().noOcclusion().pushReaction(PushReaction.DESTROY).strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_BARS = register("shadoline_bars", IronBarsBlock::new, BlockBehaviour.Properties.of().sound(ModSounds.SHADOLINE).noOcclusion().requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_CHAIN = register("shadoline_chain", ChainBlock::new, BlockBehaviour.Properties.of().sound(SoundType.CHAIN).noOcclusion().forceSolidOn().requiresCorrectToolForDrops().strength(5.0F, 6.0F), true);
    public static final Block SHADOLINE_LANTERN = register("shadoline_lantern", LanternBlock::new, BlockBehaviour.Properties.of().lightLevel(state -> 15).sound(SoundType.LANTERN).mapColor(MapColor.WARPED_NYLIUM).pushReaction(PushReaction.DESTROY).requiresCorrectToolForDrops().noOcclusion().strength(3.5f, 3.5f), true);

    // DECORATIVE BLOCKS (1)

    public static final Block SOUL_GLASS = register("soul_glass", TransparentBlock::new, BlockBehaviour.Properties.of().sound(SoundType.GLASS).instrument(NoteBlockInstrument.HAT).strength(0.6F, 0.6F).noOcclusion().isValidSpawn(Blocks::never).isRedstoneConductor(Blocks::never).isSuffocating(Blocks::never).isViewBlocking(Blocks::never), true);

    public static void initialize() {

        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.BUILDING_BLOCKS).register((itemgroup) -> {
            itemgroup.accept(PALLID_MAGNIA);
            itemgroup.accept(UMBRAL_MAGNIA);
            itemgroup.accept(POLISHED_STONE);
            itemgroup.accept(POLISHED_STONE_STAIRS);
            itemgroup.accept(POLISHED_STONE_SLAB);
            itemgroup.accept(POLISHED_STONE_WALL);
            itemgroup.accept(CRACKED_STONE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_STONE_BRICK_SLAB);
            itemgroup.accept(CRACKED_STONE_BRICK_WALL);
            itemgroup.accept(SMOOTH_STONE_STAIRS);
            itemgroup.accept(SMOOTH_STONE_WALL);
            itemgroup.accept(POLISHED_ANDESITE_WALL);
            itemgroup.accept(ANDESITE_BRICKS);
            itemgroup.accept(ANDESITE_BRICK_STAIRS);
            itemgroup.accept(ANDESITE_BRICK_SLAB);
            itemgroup.accept(ANDESITE_BRICK_WALL);
            itemgroup.accept(CRACKED_ANDESITE_BRICKS);
            itemgroup.accept(CRACKED_ANDESITE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_ANDESITE_BRICK_SLAB);
            itemgroup.accept(CRACKED_ANDESITE_BRICK_WALL);
            itemgroup.accept(CHISELED_ANDESITE);
            itemgroup.accept(POLISHED_DIORITE_WALL);
            itemgroup.accept(DIORITE_BRICKS);
            itemgroup.accept(DIORITE_BRICK_STAIRS);
            itemgroup.accept(DIORITE_BRICK_SLAB);
            itemgroup.accept(DIORITE_BRICK_WALL);
            itemgroup.accept(CRACKED_DIORITE_BRICKS);
            itemgroup.accept(CRACKED_DIORITE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_DIORITE_BRICK_SLAB);
            itemgroup.accept(CRACKED_DIORITE_BRICK_WALL);
            itemgroup.accept(CHISELED_DIORITE);
            itemgroup.accept(POLISHED_GRANITE_WALL);
            itemgroup.accept(GRANITE_BRICKS);
            itemgroup.accept(GRANITE_BRICK_STAIRS);
            itemgroup.accept(GRANITE_BRICK_SLAB);
            itemgroup.accept(GRANITE_BRICK_WALL);
            itemgroup.accept(CRACKED_GRANITE_BRICKS);
            itemgroup.accept(CRACKED_GRANITE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_GRANITE_BRICK_SLAB);
            itemgroup.accept(CRACKED_GRANITE_BRICK_WALL);
            itemgroup.accept(CHISELED_GRANITE);
            itemgroup.accept(CRACKED_DEEPSLATE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_DEEPSLATE_BRICK_SLAB);
            itemgroup.accept(CRACKED_DEEPSLATE_BRICK_WALL);
            itemgroup.accept(CRACKED_DEEPSLATE_TILE_STAIRS);
            itemgroup.accept(CRACKED_DEEPSLATE_TILE_SLAB);
            itemgroup.accept(CRACKED_DEEPSLATE_TILE_WALL);
            itemgroup.accept(CRACKED_TUFF_BRICKS);
            itemgroup.accept(CRACKED_TUFF_BRICK_STAIRS);
            itemgroup.accept(CRACKED_TUFF_BRICK_SLAB);
            itemgroup.accept(CRACKED_TUFF_BRICK_WALL);
            itemgroup.accept(POLISHED_DRIPSTONE);
            itemgroup.accept(POLISHED_DRIPSTONE_STAIRS);
            itemgroup.accept(POLISHED_DRIPSTONE_SLAB);
            itemgroup.accept(POLISHED_DRIPSTONE_WALL);
            itemgroup.accept(DRIPSTONE_BRICKS);
            itemgroup.accept(DRIPSTONE_BRICK_STAIRS);
            itemgroup.accept(DRIPSTONE_BRICK_SLAB);
            itemgroup.accept(DRIPSTONE_BRICK_WALL);
            itemgroup.accept(CRACKED_DRIPSTONE_BRICKS);
            itemgroup.accept(CRACKED_DRIPSTONE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_DRIPSTONE_BRICK_SLAB);
            itemgroup.accept(CRACKED_DRIPSTONE_BRICK_WALL);
            itemgroup.accept(CHISELED_DRIPSTONE);
            itemgroup.accept(CRACKED_CINNABAR_BRICKS);
            itemgroup.accept(CRACKED_CINNABAR_BRICK_STAIRS);
            itemgroup.accept(CRACKED_CINNABAR_BRICK_SLAB);
            itemgroup.accept(CRACKED_CINNABAR_BRICK_WALL);
            itemgroup.accept(CRACKED_SULFUR_BRICKS);
            itemgroup.accept(CRACKED_SULFUR_BRICK_STAIRS);
            itemgroup.accept(CRACKED_SULFUR_BRICK_SLAB);
            itemgroup.accept(CRACKED_SULFUR_BRICK_WALL);
            itemgroup.accept(POLISHED_CALCITE);
            itemgroup.accept(POLISHED_CALCITE_STAIRS);
            itemgroup.accept(POLISHED_CALCITE_SLAB);
            itemgroup.accept(POLISHED_CALCITE_WALL);
            itemgroup.accept(CALCITE_BRICKS);
            itemgroup.accept(CALCITE_BRICK_STAIRS);
            itemgroup.accept(CALCITE_BRICK_SLAB);
            itemgroup.accept(CALCITE_BRICK_WALL);
            itemgroup.accept(CRACKED_CALCITE_BRICKS);
            itemgroup.accept(CRACKED_CALCITE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_CALCITE_BRICK_SLAB);
            itemgroup.accept(CRACKED_CALCITE_BRICK_WALL);
            itemgroup.accept(CHISELED_CALCITE);
            itemgroup.accept(POLISHED_SANDSTONE_WALL);
            itemgroup.accept(SANDSTONE_BRICK_STAIRS);
            itemgroup.accept(SANDSTONE_BRICK_WALL);
            itemgroup.accept(CRACKED_SANDSTONE_BRICKS);
            itemgroup.accept(CRACKED_SANDSTONE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_SANDSTONE_BRICK_SLAB);
            itemgroup.accept(CRACKED_SANDSTONE_BRICK_WALL);
            itemgroup.accept(POLISHED_RED_SANDSTONE_WALL);
            itemgroup.accept(RED_SANDSTONE_BRICK_STAIRS);
            itemgroup.accept(RED_SANDSTONE_BRICK_WALL);
            itemgroup.accept(CRACKED_RED_SANDSTONE_BRICKS);
            itemgroup.accept(CRACKED_RED_SANDSTONE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_RED_SANDSTONE_BRICK_SLAB);
            itemgroup.accept(CRACKED_RED_SANDSTONE_BRICK_WALL);
            itemgroup.accept(PRISMARINE_BRICK_WALL);
            itemgroup.accept(DARK_PRISMARINE_WALL);
            itemgroup.accept(CRACKED_BLACKSTONE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_BLACKSTONE_BRICK_SLAB);
            itemgroup.accept(CRACKED_BLACKSTONE_BRICK_WALL);
            itemgroup.accept(POLISHED_BASALT);
            itemgroup.accept(POLISHED_BASALT_STAIRS);
            itemgroup.accept(POLISHED_BASALT_SLAB);
            itemgroup.accept(POLISHED_BASALT_WALL);
            itemgroup.accept(BASALT_BRICKS);
            itemgroup.accept(BASALT_BRICK_STAIRS);
            itemgroup.accept(BASALT_BRICK_SLAB);
            itemgroup.accept(BASALT_BRICK_WALL);
            itemgroup.accept(CRACKED_BASALT_BRICKS);
            itemgroup.accept(CRACKED_BASALT_BRICK_STAIRS);
            itemgroup.accept(CRACKED_BASALT_BRICK_SLAB);
            itemgroup.accept(CRACKED_BASALT_BRICK_WALL);
            itemgroup.accept(BASALT_TILES);
            itemgroup.accept(BASALT_TILE_STAIRS);
            itemgroup.accept(BASALT_TILE_SLAB);
            itemgroup.accept(BASALT_TILE_WALL);
            itemgroup.accept(CRACKED_BASALT_TILES);
            itemgroup.accept(CRACKED_BASALT_TILE_STAIRS);
            itemgroup.accept(CRACKED_BASALT_TILE_SLAB);
            itemgroup.accept(CRACKED_BASALT_TILE_WALL);
            itemgroup.accept(CHISELED_BASALT);
            itemgroup.accept(ENGRAVED_BASALT);
            itemgroup.accept(POLISHED_QUARTZ_WALL);
            itemgroup.accept(QUARTZ_BRICK_STAIRS);
            itemgroup.accept(QUARTZ_BRICK_SLAB);
            itemgroup.accept(QUARTZ_BRICK_WALL);
            itemgroup.accept(CRACKED_QUARTZ_BRICKS);
            itemgroup.accept(CRACKED_QUARTZ_BRICK_STAIRS);
            itemgroup.accept(CRACKED_QUARTZ_BRICK_SLAB);
            itemgroup.accept(CRACKED_QUARTZ_BRICK_WALL);
            itemgroup.accept(CRACKED_BRICKS);
            itemgroup.accept(CRACKED_BRICK_STAIRS);
            itemgroup.accept(CRACKED_BRICK_SLAB);
            itemgroup.accept(CRACKED_BRICK_WALL);
            itemgroup.accept(CRACKED_NETHER_BRICK_STAIRS);
            itemgroup.accept(CRACKED_NETHER_BRICK_SLAB);
            itemgroup.accept(CRACKED_NETHER_BRICK_WALL);
            itemgroup.accept(CRACKED_RED_NETHER_BRICKS);
            itemgroup.accept(CRACKED_RED_NETHER_BRICK_STAIRS);
            itemgroup.accept(CRACKED_RED_NETHER_BRICK_SLAB);
            itemgroup.accept(CRACKED_RED_NETHER_BRICK_WALL);
            itemgroup.accept(CHISELED_RED_NETHER_BRICKS);
            itemgroup.accept(CRACKED_RESIN_BRICKS);
            itemgroup.accept(CRACKED_RESIN_BRICK_STAIRS);
            itemgroup.accept(CRACKED_RESIN_BRICK_SLAB);
            itemgroup.accept(CRACKED_RESIN_BRICK_WALL);
            itemgroup.accept(POLISHED_PACKED_MUD);
            itemgroup.accept(POLISHED_PACKED_MUD_STAIRS);
            itemgroup.accept(POLISHED_PACKED_MUD_SLAB);
            itemgroup.accept(POLISHED_PACKED_MUD_WALL);
            itemgroup.accept(CRACKED_PACKED_MUD_BRICKS);
            itemgroup.accept(CRACKED_PACKED_MUD_BRICK_STAIRS);
            itemgroup.accept(CRACKED_PACKED_MUD_BRICK_SLAB);
            itemgroup.accept(CRACKED_PACKED_MUD_BRICK_WALL);
            itemgroup.accept(CHISELED_PACKED_MUD);
            itemgroup.accept(POLISHED_END_STONE);
            itemgroup.accept(POLISHED_END_STONE_STAIRS);
            itemgroup.accept(POLISHED_END_STONE_SLAB);
            itemgroup.accept(POLISHED_END_STONE_WALL);
            itemgroup.accept(CRACKED_END_STONE_BRICKS);
            itemgroup.accept(CRACKED_END_STONE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_END_STONE_BRICK_SLAB);
            itemgroup.accept(CRACKED_END_STONE_BRICK_WALL);
            itemgroup.accept(CHISELED_END_STONE);
            itemgroup.accept(POLISHED_KURODITE);
            itemgroup.accept(POLISHED_KURODITE_STAIRS);
            itemgroup.accept(POLISHED_KURODITE_SLAB);
            itemgroup.accept(POLISHED_KURODITE_WALL);
            itemgroup.accept(KURODITE_BRICKS);
            itemgroup.accept(KURODITE_BRICK_STAIRS);
            itemgroup.accept(KURODITE_BRICK_SLAB);
            itemgroup.accept(KURODITE_BRICK_WALL);
            itemgroup.accept(CRACKED_KURODITE_BRICKS);
            itemgroup.accept(CRACKED_KURODITE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_KURODITE_BRICK_SLAB);
            itemgroup.accept(CRACKED_KURODITE_BRICK_WALL);
            itemgroup.accept(CHISELED_KURODITE);
            itemgroup.accept(POLISHED_VERADITE);
            itemgroup.accept(POLISHED_VERADITE_STAIRS);
            itemgroup.accept(POLISHED_VERADITE_SLAB);
            itemgroup.accept(POLISHED_VERADITE_WALL);
            itemgroup.accept(VERADITE_BRICKS);
            itemgroup.accept(VERADITE_BRICK_STAIRS);
            itemgroup.accept(VERADITE_BRICK_SLAB);
            itemgroup.accept(VERADITE_BRICK_WALL);
            itemgroup.accept(CRACKED_VERADITE_BRICKS);
            itemgroup.accept(CRACKED_VERADITE_BRICK_STAIRS);
            itemgroup.accept(CRACKED_VERADITE_BRICK_SLAB);
            itemgroup.accept(CRACKED_VERADITE_BRICK_WALL);
            itemgroup.accept(CHISELED_VERADITE);
            itemgroup.accept(PURPUR_WALL);
            itemgroup.accept(CHISELED_PURPUR);
            itemgroup.accept(CUT_IRON);
            itemgroup.accept(CUT_IRON_STAIRS);
            itemgroup.accept(CUT_IRON_SLAB);
            itemgroup.accept(CHISELED_IRON);
            itemgroup.accept(IRON_GRATE);
            itemgroup.accept(IRON_BULB);
            itemgroup.accept(CUT_GOLD);
            itemgroup.accept(CUT_GOLD_STAIRS);
            itemgroup.accept(CUT_GOLD_SLAB);
            itemgroup.accept(CHISELED_GOLD);
            itemgroup.accept(GOLD_GRATE);
            itemgroup.accept(GOLD_BULB);
            itemgroup.accept(GOLD_DOOR);
            itemgroup.accept(GOLD_TRAPDOOR);
            itemgroup.accept(GOLD_BARS);
            itemgroup.accept(GOLD_CHAIN);
            itemgroup.accept(SHADOLINE_BLOCK);
            itemgroup.accept(CUT_SHADOLINE);
            itemgroup.accept(CUT_SHADOLINE_STAIRS);
            itemgroup.accept(CUT_SHADOLINE_SLAB);
            itemgroup.accept(CHISELED_SHADOLINE);
            itemgroup.accept(SHADOLINE_GRATE);
            itemgroup.accept(SHADOLINE_BULB);
            itemgroup.accept(SHADOLINE_DOOR);
            itemgroup.accept(SHADOLINE_TRAPDOOR);
            itemgroup.accept(SHADOLINE_BARS);
            itemgroup.accept(SHADOLINE_CHAIN);
        });

        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.NATURAL_BLOCKS).register((itemgroup) -> {
            itemgroup.accept(SILT);
            itemgroup.accept(SOULSLATE);
            itemgroup.accept(KURODITE);
            itemgroup.accept(VERADITE);
            itemgroup.accept(PALLID_MAGNIA);
            itemgroup.accept(UMBRAL_MAGNIA);
            itemgroup.accept(NETHERRACK_GLOWSTONE_ORE);
            itemgroup.accept(RAW_SHADOLINE_BLOCK);
            itemgroup.accept(WILD_WHEAT);
            itemgroup.accept(WILD_CARROT);
            itemgroup.accept(WILD_POTATO);
            itemgroup.accept(WILD_BEETROOT);
            itemgroup.accept(PONTEDERIA);
            itemgroup.accept(HIBISCUS);
            itemgroup.accept(POKER);
            itemgroup.accept(BLACK_STINKHORN);
            itemgroup.accept(WHITE_STINKHORN);
            itemgroup.accept(BUSY_LIZZIE);
            itemgroup.accept(GOLDENROD);
            itemgroup.accept(BARLEY);
            itemgroup.accept(SEA_OATS);
            itemgroup.accept(PAMPAS);
            itemgroup.accept(ICY_IRIS);
            itemgroup.accept(TALL_ICY_IRIS);
            itemgroup.accept(CLOVERS);
            itemgroup.accept(EMBER_SPROUTS);
        });

        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.FUNCTIONAL_BLOCKS).register((itemgroup) -> {
            itemgroup.accept(IRON_BULB);
            itemgroup.accept(GOLD_BULB);
            itemgroup.accept(SHADOLINE_BULB);
            itemgroup.accept(GOLD_LANTERN);
            itemgroup.accept(SHADOLINE_LANTERN);
        });

        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.REDSTONE_BLOCKS).register((itemgroup) -> {
            itemgroup.accept(IRON_BULB);
            itemgroup.accept(GOLD_BULB);
            itemgroup.accept(SHADOLINE_LANTERN);
        });

        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.COLORED_BLOCKS).register((itemgroup) -> {
            itemgroup.accept(SOUL_GLASS);
        });

    }

    private static Block register(String name, Function<BlockBehaviour.Properties, Block> blockFactory, BlockBehaviour.Properties settings, boolean registerItem) {

        ResourceKey<Block> blockKey = keyOfBlock(name);
        Block block = blockFactory.apply(settings.setId(blockKey));

        if (registerItem) {ResourceKey<Item> itemKey = keyOfItem(name);BlockItem blockItem = new BlockItem(block, new Item.Properties().setId(itemKey).useBlockDescriptionPrefix());Registry.register(BuiltInRegistries.ITEM, itemKey, blockItem);
        }

        return Registry.register(BuiltInRegistries.BLOCK, blockKey, block);

    }

    private static ResourceKey<Block> keyOfBlock(String name) {
        return ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(MOD_ID, name));
    }

    private static ResourceKey<Item> keyOfItem(String name) {
        return ResourceKey.create(Registries.ITEM, Identifier.fromNamespaceAndPath(MOD_ID, name));
    }

}